version: '3.7'

services:
    frontend:
        container_name: expense-system-frontend
        build:
            dockerfile: Dockerfile
            context: .
        depends_on:
            - revproxy
        # ports:
        #     - '3000:80'
    revproxy:
        build:
            dockerfile: Dockerfile
            context: ./.nginx
        ports:
            - '80:80'
