apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: argocd

images:
- name: matheusjustino/expense-system-react-app
  newName: matheusjustino/expense-system-react-app
  newTag: f9448a4e0cb9684626df19c79ec6cde8a25abf5d
