apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: expense-system

images:
- name: matheusjustino/expense-system-react-app
  newName: matheusjustino/expense-system-react-app
  newTag: ad87bef8b98c29ddbd105c713cf9bff44bf4ce96
