name: PROD - CI/CD
on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install --frozen-lockfile
      - run: yarn format
      - run: yarn lint
      - run: yarn build

      - name: Build image and push to docker hub
        uses: docker/build-push-action@v1.1.0
        with:
          username: matheusjustino
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          repository: matheusjustino/expense-system-react-app
          tags: ${{ github.sha }}, latest

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize_version: v3.6.1

      - name: Update k8s
        run: |
          cd k8s
          kustomize edit set image matheusjustino/expense-system-react-app=matheusjustino/expense-system-react-app:${{ github.sha }}
          cat kustomization.yaml

      - name: Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Deploy Action"
          git commit -am "Change image tag"

      - name: Push
        uses: ad-m/github-push-action@master
